name: Build and Release

on:
    push:
        branches:
            - production
    workflow_dispatch:

jobs:
    build_and_release:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # Specify your Node.js version here

            - name: Install dependencies
              run: npm install

            - name: Build the project
              run: npm run build

            - name: Archive production artifacts
              run: tar -czf build.tar.gz dist

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                tag: ${{ github.sha }}
                name: Release ${{ github.sha }}
                body: Build of commit ${{ github.sha }}
                draft: false
                prerelease: false
                artifacts: build.tar.gz
                token: ${{ secrets.GITHUB_TOKEN }}
